# Generated by Django 5.2.1 on 2025-05-28 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='featured_image',
            field=models.ImageField(blank=True, default='image.png', null=True, upload_to='blog_img'),
        ),
    ]
