# Generated by Django 5.2.1 on 2025-06-05 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_alter_blog_featured_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JobTitle',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='jobTitle',
            new_name='name',
        ),
    ]
